import { doc, getDocs, collection, writeBatch, deleteDoc } from 'firebase/firestore';
import { db } from './firebase';
import { TeacherProfile, InstituteProfile, Lecture, Playlist, Batch, TrustScoreBreakdown } from './types';

export async function seedInitialDatabase() {
  try {
    // Check if we already have the rich database to avoid re-seeding endlessly in standard sessions
    const snapPlaylists = await getDocs(collection(db, 'playlists'));
    
    // If we already have the full directory, skip seeding
    if (snapPlaylists.size >= 40) {
      console.log('Database already populated with rich JEE/NEET content. Skipping seeding.');
      return;
    }

    console.log('Seeding official JEE and NEET ecosystems database with real validated URLs...');
    
    // Clear old small seeds to prevent duplicates or clean up stale testing items
    const oldLectures = await getDocs(collection(db, 'lectures'));
    const oldPlaylists = await getDocs(collection(db, 'playlists'));
    const oldBatches = await getDocs(collection(db, 'batches'));
    const oldTeachers = await getDocs(collection(db, 'teachers'));
    const oldInstitutes = await getDocs(collection(db, 'institutes'));
    const oldTrust = await getDocs(collection(db, 'trustScores'));

    const clearBatch = writeBatch(db);
    oldLectures.docs.forEach(d => clearBatch.delete(d.ref));
    oldPlaylists.docs.forEach(d => clearBatch.delete(d.ref));
    oldBatches.docs.forEach(d => clearBatch.delete(d.ref));
    oldTeachers.docs.forEach(d => clearBatch.delete(d.ref));
    oldInstitutes.docs.forEach(d => clearBatch.delete(d.ref));
    oldTrust.docs.forEach(d => clearBatch.delete(d.ref));
    await clearBatch.commit();
    
    console.log('Previous low-density seeds cleared. Proceeding with high-fidelity write...');

    const batch = writeBatch(db);
    const nowISO = new Date().toISOString();

    // 1. Institutes Seeding
    const institutes: InstituteProfile[] = [
      {
        id: 'pw',
        name: 'Physics Wallah',
        logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&auto=format&fit=crop&q=60',
        description: "India's leading edtech unicorn offering affordable, interactive live batches and specialized Youtube channels for JEE/NEET.",
        rating: 4.8,
        reviewCount: 948,
        trustScore: 95,
        followersCount: 52100,
        officialLinks: ['https://www.pw.live'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'competishun',
        name: 'Competishun',
        logo: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=150&auto=format&fit=crop&q=60',
        description: 'Kota-style highly systematic and premium preparation portal for JEE Main & Advanced, founded by Mohit Tyagi.',
        rating: 4.9,
        reviewCount: 382,
        trustScore: 97,
        followersCount: 14200,
        officialLinks: ['https://competishun.com'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'unacademy',
        name: 'Unacademy',
        logo: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=150&auto=format&fit=crop&q=60',
        description: 'Large online learning platform with subscription-based structures and offline hybrid learning touchpoints across India.',
        rating: 4.6,
        reviewCount: 612,
        trustScore: 90,
        followersCount: 41000,
        officialLinks: ['https://unacademy.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'unacademy_jee',
        name: 'Unacademy JEE',
        logo: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=150&auto=format&fit=crop&q=60',
        description: 'Dedicated YouTube channel and vertical of Unacademy specifically curated for comprehensive IIT JEE prep courses.',
        rating: 4.7,
        reviewCount: 205,
        trustScore: 92,
        followersCount: 18400,
        officialLinks: ['https://unacademy.com'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'unacademy_neet',
        name: 'Unacademy NEET',
        logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=150&auto=format&fit=crop&q=60',
        description: 'Dedicated YouTube and learning channel specialized in NEET UG Biology, Physics, and Chemistry syllabus timelines.',
        rating: 4.5,
        reviewCount: 142,
        trustScore: 88,
        followersCount: 12900,
        officialLinks: ['https://unacademy.com'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'vedantu',
        name: 'Vedantu',
        logo: 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?w=150&auto=format&fit=crop&q=60',
        description: 'Interactive live online learning platform with wave technology and comprehensive K-12 and test prep curriculums.',
        rating: 4.6,
        reviewCount: 310,
        trustScore: 89,
        followersCount: 22000,
        officialLinks: ['https://www.vedantu.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'vedantu_jee',
        name: 'Vedantu JEE Made Ejee',
        logo: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=150&auto=format&fit=crop&q=60',
        description: "Primary channel for Vedantu's high-yield Physics, Chemistry, and Mathematics revision modules and boards classes.",
        rating: 4.7,
        reviewCount: 240,
        trustScore: 91,
        followersCount: 16500,
        officialLinks: ['https://www.vedantu.com'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'neetprep',
        name: 'NEETprep',
        logo: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=150&auto=format&fit=crop&q=60',
        description: "Focus-driven academic ecosystem centered primarily on NCERT-based medical entrance preparations, founded by Kapil Sir.",
        rating: 4.8,
        reviewCount: 512,
        trustScore: 94,
        followersCount: 29000,
        officialLinks: ['https://www.neetprep.com'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'doubtnut',
        name: 'Doubtnut',
        logo: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=150&auto=format&fit=crop&q=60',
        description: 'Digital study database and doubt clearing platform offering instant video solutions and interactive class series.',
        rating: 4.4,
        reviewCount: 180,
        trustScore: 85,
        followersCount: 32000,
        officialLinks: ['https://www.doubtnut.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'allen_career',
        name: 'ALLEN Career Institute',
        logo: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=150&auto=format&fit=crop&q=60',
        description: 'Legacy offline classroom system based in Kota with major historical footprints, proven benchmarks, and premium material.',
        rating: 4.9,
        reviewCount: 780,
        trustScore: 96,
        followersCount: 45000,
        officialLinks: ['https://www.allen.ac.in'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'aakash',
        name: 'Aakash BYJU\'S',
        logo: 'https://images.unsplash.com/photo-1558021211-6d1403321394?w=150&auto=format&fit=crop&q=60',
        description: 'National test prep leader with a comprehensive network of physical centers specializing in NEET medical rank boosters.',
        rating: 4.8,
        reviewCount: 690,
        trustScore: 93,
        followersCount: 38000,
        officialLinks: ['https://www.aakash.ac.in'],
        exams: ['NEET', 'JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'motion',
        name: 'Motion Education Group',
        logo: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=150&auto=format&fit=crop&q=60',
        description: 'Premium coaching institute based in Kota, led by the legendary Nitin Vijay (NV Sir). Highly personalized system.',
        rating: 4.7,
        reviewCount: 350,
        trustScore: 92,
        followersCount: 19500,
        officialLinks: ['https://motion.ac.in'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'resonance',
        name: 'Resonance',
        logo: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=150&auto=format&fit=crop&q=60',
        description: 'Highly acclaimed Kota coaching platform providing rigid and reliable academic learning modules across IIT and medical entry.',
        rating: 4.6,
        reviewCount: 220,
        trustScore: 89,
        followersCount: 17200,
        officialLinks: ['https://www.resonance.ac.in'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'mathongo',
        name: 'MathonGo',
        logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=60',
        description: 'Mathematics-focused educational structure offering industry-standard test series, deep analytics, and exact exam mock papers.',
        rating: 4.9,
        reviewCount: 512,
        trustScore: 98,
        followersCount: 24000,
        officialLinks: ['https://www.mathongo.com'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'examrace',
        name: 'Examrace',
        logo: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=150&auto=format&fit=crop&q=60',
        description: 'Extensive educational repository and lecture library covering CBSE, NCERT, and standard competitive benchmarks worldwide.',
        rating: 4.4,
        reviewCount: 94,
        trustScore: 84,
        followersCount: 9800,
        officialLinks: ['https://www.examrace.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'learnohub',
        name: 'LearnoHub',
        logo: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=150&auto=format&fit=crop&q=60',
        description: 'Free visual digital syllabus archive led by Roshni Mukherjee, simplifying school curricula and entrance foundations.',
        rating: 4.7,
        reviewCount: 180,
        trustScore: 90,
        followersCount: 16000,
        officialLinks: ['https://www.learnohub.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'atpstar',
        name: 'ATP Star',
        logo: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5c?w=150&auto=format&fit=crop&q=60',
        description: 'Intuitive modern test preparation platform founded by Vineet Khatri, structured to optimize score ranks.',
        rating: 4.5,
        reviewCount: 110,
        trustScore: 87,
        followersCount: 13500,
        officialLinks: ['https://www.atpstar.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'khan_academy',
        name: 'Khan Academy India',
        logo: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=150&auto=format&fit=crop&q=60',
        description: 'World-renowned open license educational database with localized micro-lectures and high fidelity modules.',
        rating: 4.8,
        reviewCount: 420,
        trustScore: 96,
        followersCount: 31000,
        officialLinks: ['https://www.khanacademy.org'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'esaral',
        name: 'eSaral',
        logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=150&auto=format&fit=crop&q=60',
        description: 'Technology-driven preparation platform for JEE and NEET with premium animations, notes, and systematic study charts.',
        rating: 4.8,
        reviewCount: 204,
        trustScore: 93,
        followersCount: 15400,
        officialLinks: ['https://www.esaral.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'physics_galaxy',
        name: 'Physics Galaxy',
        logo: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=150&auto=format&fit=crop&q=60',
        description: 'Elite online physics reservoir curated by Ashish Arora, offering comprehensive concepts for JEE and NEET physics.',
        rating: 4.9,
        reviewCount: 312,
        trustScore: 96,
        followersCount: 22100,
        officialLinks: ['https://www.physicsgalaxy.com'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'vora_classes',
        name: 'Vora Classes',
        logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=60',
        description: 'Dedicated preparation portal for IIT JEE and board classes, led by Nishant Vora and Sakshi Vora.',
        rating: 4.8,
        reviewCount: 145,
        trustScore: 94,
        followersCount: 12500,
        officialLinks: ['https://www.voraclasses.com'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'apni_kaksha',
        name: 'Apni Kaksha',
        logo: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=150&auto=format&fit=crop&q=60',
        description: 'Interactive learning portal specialized in IIT JEE preparation, GOC chemistry, computer science, and board exams.',
        rating: 4.7,
        reviewCount: 189,
        trustScore: 92,
        followersCount: 18500,
        officialLinks: ['https://www.apnikaksha.net'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'biomentors',
        name: 'Biomentors Online',
        logo: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=150&auto=format&fit=crop&q=60',
        description: 'Highly disciplined online training institute specializing exclusively in NEET medical preparations, founded by Dr. Geetendra Singh.',
        rating: 4.8,
        reviewCount: 423,
        trustScore: 95,
        followersCount: 28400,
        officialLinks: ['https://www.biomentors.online'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'bewise',
        name: 'BeWise Classes',
        logo: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=150&auto=format&fit=crop&q=60',
        description: 'Focused chemistry preparation classes for NEET and board examinations, founded by Sunil Nitharwal.',
        rating: 4.7,
        reviewCount: 98,
        trustScore: 91,
        followersCount: 8400,
        officialLinks: ['https://www.bewiseclasses.com'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'sachin_sir_physics',
        name: 'Sachin Sir Physics',
        logo: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=150&auto=format&fit=crop&q=60',
        description: 'Dedicated YouTube channel and online community centered around expected NEET Questions and boards preparation.',
        rating: 4.8,
        reviewCount: 110,
        trustScore: 93,
        followersCount: 11200,
        officialLinks: ['https://sachinsirphysics.sspacademy.com'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'vedantu_biotonic',
        name: 'Vedantu BioTonic',
        logo: 'https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=150&auto=format&fit=crop&q=60',
        description: "Vedantu's premium medical and biological preparatory channel for NEET, focusing on comprehensive human and plant physiology.",
        rating: 4.7,
        reviewCount: 156,
        trustScore: 91,
         followersCount: 14500,
        officialLinks: ['https://www.vedantu.com'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'unacademy_neet_toppers',
        name: 'Unacademy NEET Toppers',
        logo: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=150&auto=format&fit=crop&q=60',
        description: "Specialized channel from Unacademy with expected questions and high-yield topic reviews for medical toppers and repeaters.",
        rating: 4.8,
        reviewCount: 142,
        trustScore: 92,
        followersCount: 16900,
        officialLinks: ['https://unacademy.com'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      }
    ];

    institutes.forEach(inst => {
      batch.set(doc(db, 'institutes', inst.id), inst);
    });

    // 2. Teachers Seeding
    const teachers: TeacherProfile[] = [
      {
        id: 'alakh_pandey',
        name: 'Alakh Pandey',
        avatar: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=150&auto=format&fit=crop&q=60',
        subject: 'Physics',
        subjects: ['Physics'],
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        bio: 'Legendary Physics expert and founder of PW. Acclaimed for his peerless explanations of classical mechanics and electromagnetism.',
        rating: 4.9,
        reviewCount: 1530,
        trustScore: 97,
        followersCount: 65400,
        officialLinks: ['https://www.youtube.com/c/PhysicsWallah/videos'],
        youtubeChannelId: 'https://www.youtube.com/c/PhysicsWallah/videos',
        officialWebsite: 'https://www.pw.live',
        socialProfiles: ['https://apps.apple.com/in/app/physics-wallah/id1641443555'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'mohit_tyagi',
        name: 'Mohit Tyagi',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=60',
        subject: 'Mathematics',
        subjects: ['Mathematics'],
        instituteId: 'competishun',
        instituteName: 'Competishun',
        bio: 'IIT Delhi Alumnus. Premier authority in Calculus, Algebra, and coordinate analytics with a deeply exhaustive visual teaching structure.',
        rating: 4.9,
        reviewCount: 924,
        trustScore: 98,
        followersCount: 41200,
        officialLinks: ['https://www.youtube.com/@MohitTyagi'],
        youtubeChannelId: 'https://www.youtube.com/@MohitTyagi',
        officialWebsite: 'https://competishun.com/',
        socialProfiles: ['https://instagram.com/competishun/?hl=en'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'nv_sir',
        name: 'Nitin Vijay (NV Sir)',
        avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=60',
        subject: 'Physics',
        subjects: ['Physics'],
        instituteId: 'motion',
        instituteName: 'Motion Education Group',
        bio: 'Legendary senior Physics mentor in Kota. Known for introducing animated real-world mechanics and visual representation slides.',
        rating: 4.8,
        reviewCount: 612,
        trustScore: 94,
        followersCount: 29800,
        officialLinks: ['https://www.youtube.com/@MotionEducation'],
        youtubeChannelId: 'https://www.youtube.com/@MotionEducation',
        officialWebsite: 'https://motion.ac.in/',
        socialProfiles: ['https://instagram.com/motionkota'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'hc_verma',
        name: 'Dr. H.C. Verma',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=60',
        subject: 'Physics',
        subjects: ['Physics'],
        bio: 'Retd. IIT Kanpur Professor. Author of the ultimate syllabus bible "Concepts of Physics". Pioneer of experimental demonstrations.',
        rating: 4.9,
        reviewCount: 2012,
        trustScore: 99,
        followersCount: 92000,
        officialLinks: ['https://www.youtube.com/@HCVermaPhysics'],
        youtubeChannelId: 'https://www.youtube.com/@HCVermaPhysics',
        officialWebsite: 'https://hcverma.in',
        socialProfiles: ['https://linkedin.com/in/hcverma'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'skm_sir',
        name: 'SURENDRA KUMAR MISHRA (SKM Sir)',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=60',
        subject: 'Organic Chemistry',
        subjects: ['Organic Chemistry', 'Chemistry'],
        instituteId: 'competishun',
        instituteName: 'Competishun',
        bio: 'Renowned expert in Organic Chemistry, explaining high-yield GOC mechanisms, reaction parameters and carbon compounds.',
        rating: 4.8,
        reviewCount: 215,
        trustScore: 94,
        followersCount: 18450,
        officialLinks: ['https://www.youtube.com/@Competishun'],
        youtubeChannelId: 'https://www.youtube.com/@Competishun',
        officialWebsite: 'https://competishun.com',
        socialProfiles: ['https://instagram.com/competishun'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'ashish_arora',
        name: 'Ashish Arora',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=60',
        subject: 'Physics',
        subjects: ['Physics'],
        instituteId: 'physics_galaxy',
        instituteName: 'Physics Galaxy',
        bio: 'Founder of Physics Galaxy. Highly acclaimed physics mentor with decades of experience training top IIT rankers.',
        rating: 4.9,
        reviewCount: 423,
        trustScore: 96,
        followersCount: 45000,
        officialLinks: ['https://www.youtube.com/@physicsgalaxyworld'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'nishant_vora',
        name: 'Nishant Vora',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=60',
        subject: 'Mathematics',
        subjects: ['Mathematics'],
        instituteId: 'vora_classes',
        instituteName: 'Vora Classes',
        bio: 'IIT Alumnus and elite mathematics educator. Acclaimed for his complete brief mathematics lectures and calculus masterclasses.',
        rating: 4.8,
        reviewCount: 198,
        trustScore: 94,
        followersCount: 32000,
        officialLinks: ['https://www.youtube.com/@voraclasses'],
        exams: ['JEE'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'sachin_sir',
        name: 'Sachin Sir',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=60',
        subject: 'Physics',
        subjects: ['Physics'],
        instituteId: 'sachin_sir_physics',
        instituteName: 'Sachin Sir Physics',
        bio: 'Passionate physics mentor and digital creator, renowned for NEET expected question series and board exam high-scoring formulas.',
        rating: 4.8,
        reviewCount: 154,
        trustScore: 93,
        followersCount: 18000,
        officialLinks: ['https://www.youtube.com/@sachinsirphysics'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'ritu_mam',
        name: 'Ritu Rattewal',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=60',
        subject: 'Biology',
        subjects: ['Biology'],
        instituteId: 'vedantu',
        instituteName: 'Vedantu',
        bio: 'Distinguished Biology expert and mentor. Celebrated for her NCERT-centric, detail-oriented lectures explaining Cell Biology and Human Physiology.',
        rating: 4.9,
        reviewCount: 654,
        trustScore: 95,
        followersCount: 54000,
        officialLinks: ['https://www.youtube.com/@RituRattewalBiology'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'akanksha_mam',
        name: 'Akanksha Mam',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=60',
        subject: 'Biology',
        subjects: ['Biology'],
        instituteId: 'etoos',
        instituteName: 'Etoos India',
        bio: 'Botany and Chemistry master educator associated with Etoos India. Famed for botany one-shots and easy concept mapping.',
        rating: 4.7,
        reviewCount: 142,
        trustScore: 91,
        followersCount: 19000,
        officialLinks: ['https://www.youtube.com/@EtoosEducation'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'roshni_mukherjee',
        name: 'Roshni Mukherjee',
        avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=60',
        subject: 'Chemistry',
        subjects: ['Chemistry', 'Physics', 'Biology'],
        instituteId: 'learnohub',
        instituteName: 'LearnoHub',
        bio: 'Founder of LearnoHub. Highly accomplished educator, simplifying complex physics, chemistry, and biology topics for lakhs of aspirants.',
        rating: 4.8,
        reviewCount: 312,
        trustScore: 95,
        followersCount: 42000,
        officialLinks: ['https://www.youtube.com/@LearnoHubClass1112'],
        exams: ['JEE', 'NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      },
      {
        id: 'sunil_nitharwal',
        name: 'Sunil Nitharwal',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=60',
        subject: 'Chemistry',
        subjects: ['Chemistry'],
        instituteId: 'bewise',
        instituteName: 'BeWise Classes',
        bio: 'Founder of BeWise Classes. Expert Chemistry faculty for NEET, simplifying General Organic Chemistry and reaction mechanisms.',
        rating: 4.8,
        reviewCount: 104,
        trustScore: 92,
        followersCount: 11000,
        officialLinks: ['https://www.youtube.com/@BeWiseClasses'],
        exams: ['NEET'],
        isVerified: true,
        verified: true,
        verificationStatus: 'verified',
        createdAt: nowISO
      }
    ];

    teachers.forEach(teacher => {
      batch.set(doc(db, 'teachers', teacher.id), teacher);
    });

    // 3. Trust Scores Breakdowns Seeding
    const scores: TrustScoreBreakdown[] = [
      {
        entityId: 'alakh_pandey',
        profileCompleteness: 3,
        verifiedCredentials: 14,
        officialLinksScore: 2,
        reviewReliability: 39,
        contentConsistency: 1.0,
        communityEngagement: 39,
        totalScore: 97,
        updatedAt: nowISO
      },
      {
        entityId: 'mohit_tyagi',
        profileCompleteness: 3,
        verifiedCredentials: 14,
        officialLinksScore: 2,
        reviewReliability: 40,
        contentConsistency: 1.0,
        communityEngagement: 40,
        totalScore: 98,
        updatedAt: nowISO
      },
      {
        entityId: 'nv_sir',
        profileCompleteness: 3,
        verifiedCredentials: 13,
        officialLinksScore: 2,
        reviewReliability: 38,
        contentConsistency: 0.9,
        communityEngagement: 38,
        totalScore: 94,
        updatedAt: nowISO
      },
      {
        entityId: 'hc_verma',
        profileCompleteness: 3,
        verifiedCredentials: 15,
        officialLinksScore: 2,
        reviewReliability: 40,
        contentConsistency: 1.0,
        communityEngagement: 40,
        totalScore: 99,
        updatedAt: nowISO
      }
    ];

    scores.forEach(score => {
      batch.set(doc(db, 'trustScores', score.entityId), score);
    });

    // 4. Playlists Seeding (Section 2 of the PDF)
    const playlists: Playlist[] = [
      {
        id: 'play_pw_alakh_pace_ktg',
        title: 'PACE Physics - Kinetic Theory of Gases',
        description: 'Complete classroom lecture series covering kinetic behavior of gases, derivation formulas, and mean free path properties.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&auto=format&fit=crop&q=80',
        teacherId: 'alakh_pandey',
        teacherName: 'Alakh Pandey',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        subject: 'Physics',
        examType: 'Both',
        lecturesCount: 6,
        youtubePlaylistId: 'PLF_7kfnwLFCHC4IqtB6vA-E_N6r8r0FnT',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLF_7kfnwLFCHC4IqtB6vA-E_N6r8r0FnT',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_jw_units',
        title: 'Units, Measurements & Error',
        description: 'High yield foundational chapter-wise course covering dimensional analysis, vernier calipers, and systematic error corrections.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80',
        teacherId: 'alakh_pandey',
        teacherName: 'JEE Wallah (PW)',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 5,
        youtubePlaylistId: 'PLxyGaR3hEy3gP8BPYdOruPYsJkHGrIXj8',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLxyGaR3hEy3gP8BPYdOruPYsJkHGrIXj8',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_jw_basic_math',
        title: 'Basic Mathematics in Physics',
        description: 'Mathematical tools and mathematical revision prerequisite series explaining differentiation integration and vector analysis.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&auto=format&fit=crop&q=80',
        teacherId: 'alakh_pandey',
        teacherName: 'JEE Wallah (PW)',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 8,
        youtubePlaylistId: 'PLrjNVPtTTXzQVdUCRFsH_81x0oQhT2hFj',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLrjNVPtTTXzQVdUCRFsH_81x0oQhT2hFj',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_jw_mechanics_rj',
        title: 'Mechanics Comprehensive Course (Rj Sir)',
        description: 'Exhaustive chapter series tracking Kinematics, Newton\'s Laws, Work Power Energy, Rotational Motion and Fluid dynamics.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1461532252243-8533b3e817be?w=400&auto=format&fit=crop&q=80',
        teacherId: 'alakh_pandey',
        teacherName: 'Rj Sir',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 22,
        youtubePlaylistId: 'PL7ZGw_gkbYzsmjam3sn610gSKyaxrng4r',
        sourceUrl: 'https://m.youtube.com/playlist?list=PL7ZGw_gkbYzsmjam3sn610gSKyaxrng4r',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_comp_kinematics',
        title: 'Rectilinear Motion & Kinematics',
        description: 'Detail-oriented Kota prep lectures covering displacement, reference frames, relative motion, and 2D mechanics formulas.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'Mohit Tyagi',
        instituteId: 'competishun',
        instituteName: 'Competishun',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 14,
        youtubePlaylistId: 'PLGw1nv-9_t1OEyCQAec2vIQbuHKbABF05',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLGw1nv-9_t1OEyCQAec2vIQbuHKbABF05',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_comp_goc',
        title: 'General Organic Chemistry (GOC-1)',
        description: 'Exhaustive molecular mechanics series on carbon chains, electromeric effects, inductive parameters and nucleophiles by SKM Sir.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=400&auto=format&fit=crop&q=80',
        teacherId: 'skm_sir',
        teacherName: 'SKM Sir',
        instituteId: 'competishun',
        instituteName: 'Competishun',
        subject: 'Organic Chemistry',
        examType: 'JEE',
        lecturesCount: 18,
        youtubePlaylistId: 'PLLeMwkOo4I8u8cFHmfWtIMek6kqWs8B8Sr',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLLeMwkOo4I8u8cFHmfWtIMek6kqWs8B8Sr',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_unac_current',
        title: 'Current Electricity - JEE Series',
        description: 'Master circuits, Kirchhoff\'s Laws, drift velocity and potential logs with Unacademy expert teachers.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'Unacademy JEE',
        instituteId: 'unacademy_jee',
        instituteName: 'Unacademy',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 10,
        youtubePlaylistId: 'PLbu_fGT0MPssBASDfJI-8qFcnXReAcyPi',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLbu_fGT0MPssBASDfJI-8qFcnXReAcyPi',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_unac_amines',
        title: 'Amines & Nitrogen Compounds by Anupam Gupta',
        description: 'High-concept lecture series analyzing basicity parameters, preparation steps, and identification mechanisms.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'Anupam Gupta',
        instituteId: 'unacademy_jee',
        instituteName: 'Unacademy',
        subject: 'Organic Chemistry',
        examType: 'JEE',
        lecturesCount: 12,
        youtubePlaylistId: 'PLbu_fGT0MPsus9JpqVyGCN57XYXnzJgCP',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLbu_fGT0MPsus9JpqVyGCN57XYXnzJgCP',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ved_adv_kinematics',
        title: 'Advanced Kinematics - Vedantu JEE English',
        description: 'Full syllabus chapter revision on mechanics in English. Designed for international standard students and national level aspirants.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Vedantu JEE English',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 8,
        youtubePlaylistId: 'PL24P3-cdGKKsOqwW86IWK1CR65BXLvfkJ',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL24P3-cdGKKsOqwW86IWK1CR65BXLvfkJ',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ved_physical_formula',
        title: 'Formula Revision - Physical Chemistry',
        description: 'Interactive session covering active formulas of solid state, electrochemistry, equilibrium and kinetic parameters in English.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1532187863486-abf9d39d66e8?w=400&auto=format&fit=crop&q=80',
        teacherId: 'skm_sir',
        teacherName: 'Vedantu JEE English',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        subject: 'Physical Chemistry',
        examType: 'JEE',
        lecturesCount: 9,
        youtubePlaylistId: 'PL24P3-cdGKKukaFYgKhyLmMcvlu_ipYOA',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL24P3-cdGKKukaFYgKhyLmMcvlu_ipYOA',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ved_redox',
        title: 'Redox Reactions, States of Matter, Ideal Gas',
        description: 'Syllabus lectures covering oxidation states, balancing equations, Boyle\'s and Charles\' Laws, real gas equations.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511225010778-19335a434b81?w=400&auto=format&fit=crop&q=80',
        teacherId: 'skm_sir',
        teacherName: 'Vedantu JEE English',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        subject: 'Physical Chemistry',
        examType: 'JEE',
        lecturesCount: 11,
        youtubePlaylistId: 'PL24P3-cdGKKtUqz33RG1FsfbPdeXagW7F',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL24P3-cdGKKtUqz33RG1FsfbPdeXagW7F',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ved_stats',
        title: 'JEE Mathematics - Statistics',
        description: 'Exhaustive formulas, mean, variance, standard deviation parameters, and past years JEE exam questions analytical revisions.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509228626622-a61247a3b42a?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'Vedantu JEE',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        subject: 'Mathematics',
        examType: 'JEE',
        lecturesCount: 4,
        youtubePlaylistId: 'PLCtUyOrCJbxw21Gl7aom58uYGSkCe1C9A',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLCtUyOrCJbxw21Gl7aom58uYGSkCe1C9A',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_neetprep_bio_revision',
        title: 'Short Revision Biology (Dr. NK Sharma)',
        description: 'NCERT based medical prep lessons explaining evolution, origin of life, proteins structure, and biomolecules.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&auto=format&fit=crop&q=80',
        teacherId: 'hc_verma',
        teacherName: 'Dr. NK Sharma',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 15,
        youtubePlaylistId: 'PLpLDwT9Mi15UsCjVCFrt_JdBFNXuEJGLc',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLpLDwT9Mi15UsCjVCFrt_JdBFNXuEJGLc',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_neetprep_expected',
        title: 'Expected Biology Questions (Vipin & Vivek Sir)',
        description: 'NCERT master line practice focusing on Human Physiology and Botanical classification patterns.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=400&auto=format&fit=crop&q=80',
        teacherId: 'hc_verma',
        teacherName: 'Vipin & Vivek Sir',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 12,
        youtubePlaylistId: 'PLpLDwT9Mi15VnFnrkUri5VM0S0UqJl9u5',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLpLDwT9Mi15VnFnrkUri5VM0S0UqJl9u5',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_neetprep_genetics',
        title: 'NEET Genetics & Reproduction',
        description: 'Detailed analysis of Human Reproduction, Plant Sex Reproduction, Mendel\'s laws, and taxonomic classification.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1579124476582-fc18276f16ab?w=400&auto=format&fit=crop&q=80',
        teacherId: 'hc_verma',
        teacherName: 'NEETprep Course',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 20,
        youtubePlaylistId: 'PLpLDwT9Mi15U2ryCl6DV5bYDTXUCC26Rx',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLpLDwT9Mi15U2ryCl6DV5bYDTXUCC26Rx',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_neetprep_rotational',
        title: 'Rotational Motion for Medical Aspirants',
        description: 'Simplifying torque, moment of inertia, angular momentum, and kinematics parameters for NEET level exams.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Vivek Sir',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        subject: 'Physics',
        examType: 'NEET',
        lecturesCount: 6,
        youtubePlaylistId: 'PLpLDwT9Mi15Wcw1o8PZttaD8LrpHjSrHu',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLpLDwT9Mi15Wcw1o8PZttaD8LrpHjSrHu',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_allen_sir',
        title: 'ALLEN Selective Interactive Revision (SIR)',
        description: 'Premium revision crash courses covering selective high yielding topics in PCM and PCB streams.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'ALLEN Kota experts',
        instituteId: 'allen_career',
        instituteName: 'ALLEN Career Institute',
        subject: 'Physics',
        examType: 'Both',
        lecturesCount: 30,
        youtubePlaylistId: 'PL46TqiNVZpK_ES5P_fh4xtBq8rX_XP3Jq',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL46TqiNVZpK_ES5P_fh4xtBq8rX_XP3Jq',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_mat_jee2027',
        title: 'JEE 2027 Mathematics Foundation',
        description: 'In-depth conceptual lectures covering sets, relations, functions, logarithms, and coordinate basics.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'MathonGo',
        instituteId: 'mathongo',
        instituteName: 'MathonGo',
        subject: 'Mathematics',
        examType: 'JEE',
        lecturesCount: 16,
        youtubePlaylistId: 'PLDJktDT5uc9unhs-P1mWDcnNrgzPbwxHX',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLDJktDT5uc9unhs-P1mWDcnNrgzPbwxHX',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_unac_living',
        title: 'The Living World (Dr. Sachin Kapur)',
        description: 'Exhaustive medical entrance series introducing taxonomical hierarchies, biological nomenclature, and herbarium systems.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
        teacherId: 'hc_verma',
        teacherName: 'Dr. Sachin Kapur',
        instituteId: 'unacademy_neet',
        instituteName: 'Unacademy',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 5,
        youtubePlaylistId: 'PLsgHooHkqhhNWiiYtSlpdjPEVYhHqtCkR',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLsgHooHkqhhNWiiYtSlpdjPEVYhHqtCkR',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_unac_phys_journey',
        title: 'Complete Physics Journey by Anupam Sir',
        description: 'Medical level concepts ranging from kinematics to mechanics, thermodynamics, electromagnetism and modern physics.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Anupam Sir',
        instituteId: 'unacademy_neet',
        instituteName: 'Unacademy',
        subject: 'Physics',
        examType: 'NEET',
        lecturesCount: 25,
        youtubePlaylistId: 'PLsgHooHkqhhNENfI57u4dLXvlG-oRFSx6',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLsgHooHkqhhNENfI57u4dLXvlG-oRFSx6',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_motion_chemical_bonding',
        title: 'Chemical Bonding (NEET DLP NV Sir)',
        description: 'Molecular geometry, covalent bonding, hybridizations, and VSEPR theories designed by Kota faculty.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5c?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Nitin Vijay (NV Sir)',
        instituteId: 'motion',
        instituteName: 'Motion Education Group',
        subject: 'Inorganic Chemistry',
        examType: 'NEET',
        lecturesCount: 14,
        youtubePlaylistId: 'PLDrgDtCLUcebZmYQCxZq9qXbpFF5gy7Cl',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLDrgDtCLUcebZmYQCxZq9qXbpFF5gy7Cl',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_motion_electrochemistry',
        title: 'Electrochemistry (NEET DLP NV Sir)',
        description: 'Detailed analysis of redox reaction EMF, Nernst equations, electrolysis, and electrical conductivity profiles.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Nitin Vijay (NV Sir)',
        instituteId: 'motion',
        instituteName: 'Motion Education Group',
        subject: 'Physical Chemistry',
        examType: 'NEET',
        lecturesCount: 12,
        youtubePlaylistId: 'PLDrgDtCLUceYqilsrasSo94Y58lrqrX2h',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLDrgDtCLUceYqilsrasSo94Y58lrqrX2h',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_motion_abhyaas_physics',
        title: 'JEE FREE Abhyaas Physics Course',
        description: 'Rank booster practice problems solving live sessions, covering complex coordinate mechanics and optics derivations.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Motion Kota Faculty',
        instituteId: 'motion',
        instituteName: 'Motion Education Group',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 18,
        youtubePlaylistId: 'PLZYt2g8epPytFGIv5hGR2PoQ7-ggMVptL',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLZYt2g8epPytFGIv5hGR2PoQ7-ggMVptL',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_doubtnut_neet_hindi',
        title: 'Doubtnut NEET 2021 Hindi Medium Physics',
        description: 'Complete syllabus physics courses strictly in Hindi medium covering Newtonian mechanics and fluid equations.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&auto=format&fit=crop&q=80',
        teacherId: 'hc_verma',
        teacherName: 'Doubtnut NEET Team',
        instituteId: 'doubtnut',
        instituteName: 'Doubtnut',
        subject: 'Physics',
        examType: 'NEET',
        lecturesCount: 22,
        youtubePlaylistId: 'PLYMSD3mdSJhfY3J2HPMmT1CK6OwFO5dZB',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLYMSD3mdSJhfY3J2HPMmT1CK6OwFO5dZB',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_pw_botany_30d',
        title: 'Botany in 30 Days (Photosynthesis in Higher Plants)',
        description: 'Intense and highly systematic revision of Higher Plant Photosynthesis curriculum tracks for medical competitive sectors.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1463171359979-3006d7bbaed8?w=400&auto=format&fit=crop&q=80',
        teacherId: 'akanksha_mam',
        teacherName: 'Competition Wallah Faculty',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 15,
        youtubePlaylistId: 'PLMQCP2T3gE7S_ps_4-828rBGD5sJyH-3A',
        sourceUrl: 'https://music.youtube.com/playlist?list=PLMQCP2T3gE7S_ps_4-828rBGD5sJyH-3A',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_pw_neet_mindmaps',
        title: 'RE-NEET Mindmaps - Complete Mindmap Revision',
        description: 'Rapid botanical and physiological medical syllabus overview utilizing high-contrast concept mindmaps.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=400&auto=format&fit=crop&q=80',
        teacherId: 'ritu_mam',
        teacherName: 'NEET Wallah Team',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 18,
        youtubePlaylistId: 'PLhjSf6BJN_X44GGDltTgk9cyb7ammVx7Q',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLhjSf6BJN_X44GGDltTgk9cyb7ammVx7Q',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ved_cell_life',
        title: 'Cell: The Unit of Life (Ritu Ma\'am)',
        description: 'NCERT based medical entrance lecture series detailing cell organelle structures, membranes, and cellular divisions.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=400&auto=format&fit=crop&q=80',
        teacherId: 'ritu_mam',
        teacherName: 'Ritu Rattewal',
        instituteId: 'vedantu',
        instituteName: 'Vedantu',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 8,
        youtubePlaylistId: 'PLsYnixC0bTgsVXnkVw_uAdd2hpuB1_HJw',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLsYnixC0bTgsVXnkVw_uAdd2hpuB1_HJw',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_aakash_nuclei',
        title: 'Crack JEE Physics - Nuclei',
        description: 'Elite class curriculum tracks regarding nuclear physics, radioactivity, half-life formulas, and binding energy scales.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&auto=format&fit=crop&q=80',
        teacherId: 'hc_verma',
        teacherName: 'Aakash BYJU\'S Faculty',
        instituteId: 'aakash',
        instituteName: 'Aakash BYJU\'S',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 5,
        youtubePlaylistId: 'PLDnXxcwgchDMFeUkZl6Hec8kXo3rcPL8c',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLDnXxcwgchDMFeUkZl6Hec8kXo3rcPL8c',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_res_jee_celebration',
        title: 'Exam Celebration & Analysis (JEE Main)',
        description: 'Highly acclaimed academic celebration, paper reviews, memory-based question solutions, and rank predictors.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'Resonance Faculty',
        instituteId: 'resonance',
        instituteName: 'Resonance',
        subject: 'Mathematics',
        examType: 'JEE',
        lecturesCount: 12,
        youtubePlaylistId: 'PLxj0DHzBkLyp_tuzQB7dwOZazD8z2cClR',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLxj0DHzBkLyp_tuzQB7dwOZazD8z2cClR',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_comp_maths_notes',
        title: 'Ecosystem (Maths Notes Completions)',
        description: 'Kota styled math concepts ecosystem, notes, and full syllabus track completions for JEE Main & Advanced.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&auto=format&fit=crop&q=80',
        teacherId: 'mohit_tyagi',
        teacherName: 'Mohit Tyagi',
        instituteId: 'competishun',
        instituteName: 'Competishun',
        subject: 'Mathematics',
        examType: 'JEE',
        lecturesCount: 22,
        youtubePlaylistId: 'PL0j5BiyDgD64MnNZkUMQmFhoz5Myizyvx',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL0j5BiyDgD64MnNZkUMQmFhoz5Myizyvx',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_etoos_botany_oneshots',
        title: 'Botany One-Shots (Akanksha Mam)',
        description: 'Botany revision series detailing plant physiology, cellular structures, and genetics by premium Etoos faculty.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&auto=format&fit=crop&q=80',
        teacherId: 'akanksha_mam',
        teacherName: 'Akanksha Mam',
        instituteId: 'etoos',
        instituteName: 'Etoos India',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 16,
        youtubePlaylistId: 'PLfLUMdH8_guP28iuxUgKb7cz3RpAo3wSB',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLfLUMdH8_guP28iuxUgKb7cz3RpAo3wSB',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_learn_thermodynamics',
        title: 'Thermodynamics Class 11 Chemistry',
        description: 'Interactive and visual digital syllabus archiving thermodynamic laws, enthalpy, entropy, and free energy.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
        teacherId: 'roshni_mukherjee',
        teacherName: 'Roshni Mukherjee',
        instituteId: 'learnohub',
        instituteName: 'LearnoHub',
        subject: 'Chemistry',
        examType: 'Both',
        lecturesCount: 8,
        youtubePlaylistId: 'PLCzaIJYXP5Yc8CHEi5a2LrcrYFHcjPE7r',
        sourceUrl: 'https://m.youtube.com/playlist?list=PLCzaIJYXP5Yc8CHEi5a2LrcrYFHcjPE7r',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_examrace_higher',
        title: 'Higher Education & NCERT series',
        description: 'Comprehensive CBSE, NCERT education repository and lectures on higher educational development tracks.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1513258496099-48168024aec0?w=400&auto=format&fit=crop&q=80',
        teacherId: 'roshni_mukherjee',
        teacherName: 'Examrace Experts',
        instituteId: 'examrace',
        instituteName: 'Examrace',
        subject: 'General',
        examType: 'Others',
        lecturesCount: 30,
        youtubePlaylistId: 'PL_5QGF2oYUoBM5-4qHQJpx-1vWBL8-Dbh',
        sourceUrl: 'https://music.youtube.com/playlist?list=PL_5QGF2oYUoBM5-4qHQJpx-1vWBL8-Dbh',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_atpstar_concepts',
        title: 'Frequently Asked Concepts (Physics)',
        description: 'Score optimizing lecture series targeting high yield, repeated mathematical physics questions.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nv_sir',
        teacherName: 'Vineet Khatri',
        instituteId: 'atpstar',
        instituteName: 'ATP Star',
        subject: 'Physics',
        examType: 'JEE',
        lecturesCount: 14,
        youtubePlaylistId: 'PL7rZUH8srnuNQ3FFc0rRiCt8l1ezv_U4a',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL7rZUH8srnuNQ3FFc0rRiCt8l1ezv_U4a',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_khan_metals',
        title: 'Metals and Non-Metals',
        description: 'High-yield foundational science chapters simplifying solid matter classifications, reactions, and periodic properties.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=400&auto=format&fit=crop&q=80',
        teacherId: 'roshni_mukherjee',
        teacherName: 'Khan Academy Faculty',
        instituteId: 'khan_academy',
        instituteName: 'Khan Academy India',
        subject: 'Science',
        examType: 'Foundation',
        lecturesCount: 10,
        youtubePlaylistId: 'PL2ub1_oKCn7rs_6_xfEa_Zyrp7BD3ZT_K',
        sourceUrl: 'https://m.youtube.com/playlist?list=PL2ub1_oKCn7rs_6_xfEa_Zyrp7BD3ZT_K',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_esaral_complex',
        title: 'Complex Numbers & Solution of Triangles',
        description: 'Class 11 backlog revision series providing elegant tricks, proofs, and exhaustive worksheets.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nishant_vora',
        teacherName: 'eSaral Experts',
        instituteId: 'esaral',
        instituteName: 'eSaral',
        subject: 'Mathematics',
        examType: 'JEE',
        lecturesCount: 15,
        youtubePlaylistId: 'PLMjEg73ogUEIwjpCTixpGR14epVmsh6bi',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLMjEg73ogUEIwjpCTixpGR14epVmsh6bi',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_galaxy_rigid',
        title: 'Rigid Body Dynamics & Rotational Motion',
        description: 'Onion physics series curated by Ashish Arora, simplifying rigid body systems, angular mechanics, and momentum locks.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&auto=format&fit=crop&q=80',
        teacherId: 'ashish_arora',
        teacherName: 'Ashish Arora',
        instituteId: 'physics_galaxy',
        instituteName: 'Physics Galaxy',
        subject: 'Physics',
        examType: 'Both',
        lecturesCount: 22,
        youtubePlaylistId: 'PLYVDsiuOZP5pQG7m5YePxCtrSGHnYvEmk',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLYVDsiuOZP5pQG7m5YePxCtrSGHnYvEmk',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_vora_quadratic',
        title: 'Quadratic Equations (JEE Maths Brief)',
        description: 'High caliber revision of secondary school equations, rational functions, and graphs for IIT JEE.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80',
        teacherId: 'nishant_vora',
        teacherName: 'Niant Vora',
        instituteId: 'vora_classes',
        instituteName: 'Vora Classes',
        subject: 'Mathematics',
        examType: 'JEE',
        lecturesCount: 6,
        youtubePlaylistId: 'PLiZbGZW1sixpIZD5zDjhfY3J2HPMmT1CK6OwFO5dZB',
        sourceUrl: 'https://music.youtube.com/playlist?list=PLiZbGZW1sixpIZD5zDjhfY3J2HPMmT1CK6OwFO5dZB',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_apni_goc',
        title: 'General Organic Chemistry (GOC L1) SSP',
        description: 'Advanced molecular architecture, resonance energy, induction constants, and organic pathways by SKM Sir.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=400&auto=format&fit=crop&q=80',
        teacherId: 'skm_sir',
        teacherName: 'SKM Sir',
        instituteId: 'apni_kaksha',
        instituteName: 'Apni Kaksha',
        subject: 'Organic Chemistry',
        examType: 'JEE',
        lecturesCount: 24,
        youtubePlaylistId: 'PLeMwkOo4I8u8cFHmfWtIMek6kqWs8B8Sr',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLeMwkOo4I8u8cFHmfWtIMek6kqWs8B8Sr',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_biomentors_repeaters',
        title: 'Repeaters Orientation Classes (NEET)',
        description: 'Elite and highly-disciplined training modules specifically structured for NEET repeaters and high rankers.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&auto=format&fit=crop&q=80',
        teacherId: 'ritu_mam',
        teacherName: 'Dr. Geetendra Singh',
        instituteId: 'biomentors',
        instituteName: 'Biomentors Online',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 5,
        youtubePlaylistId: 'PL2AGQm6bx5CDYLXPoi1ZHckLEYmAkVVOs',
        sourceUrl: 'https://www.youtube.com/playlist?list=PL2AGQm6bx5CDYLXPoi1ZHckLEYmAkVVOs',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_bewise_goc',
        title: 'General Organic Chemistry (NEET 2026 Strategy)',
        description: 'Easy chemistry frameworks designed specifically for medical entrance speed score optimizations.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&auto=format&fit=crop&q=80',
        teacherId: 'sunil_nitharwal',
        teacherName: 'Sunil Nitharwal',
        instituteId: 'bewise',
        instituteName: 'BeWise Classes',
        subject: 'Organic Chemistry',
        examType: 'NEET',
        lecturesCount: 15,
        youtubePlaylistId: 'PLlI_o9_av3pPj-Am4m0n6A6ozlHxQil39',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLlI_o9_av3pPj-Am4m0n6A6ozlHxQil39',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ssp_expected',
        title: 'Expected Expected NEET Questions (Fluid Mech, SHM, Waves)',
        description: 'SSP Physics selective questions and solutions, formulas revision worksheets, and boards scoring parameters.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=400&auto=format&fit=crop&q=80',
        teacherId: 'sachin_sir',
        teacherName: 'Sachin Sir',
        instituteId: 'sachin_sir_physics',
        instituteName: 'Sachin Sir Physics',
        subject: 'Physics',
        examType: 'NEET',
        lecturesCount: 10,
        youtubePlaylistId: 'PLCWm8jBxm8LJ7xVvGXhDXlGAE1nrQF6sS',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLCWm8jBxm8LJ7xVvGXhDXlGAE1nrQF6sS',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_ved_biotonic_microbes',
        title: 'Microbes in Human Welfare (BioTonic)',
        description: 'NCERT aligned botany marathon revision summarizing bacteriological, fungal, and viral helpers across ecosystem cycles.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?w=400&auto=format&fit=crop&q=80',
        teacherId: 'ritu_mam',
        teacherName: 'BioTonic Faculty',
        instituteId: 'vedantu_biotonic',
        instituteName: 'Vedantu BioTonic',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 6,
        youtubePlaylistId: 'PLw4_E5WmrJxueBpppj1K30U0xHjjGXsre',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLw4_E5WmrJxueBpppj1K30U0xHjjGXsre',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_unac_toppers_ioc',
        title: 'IOC Shift Qs, Plant Physiology (Expected Series)',
        description: 'Exhaustive analysis of inorganic chemistry structures and reactions for medical toppers and repeaters.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
        teacherId: 'sunil_nitharwal',
        teacherName: 'Unacademy Toppers Faculty',
        instituteId: 'unacademy_neet_toppers',
        instituteName: 'Unacademy NEET Toppers',
        subject: 'Inorganic Chemistry',
        examType: 'NEET',
        lecturesCount: 12,
        youtubePlaylistId: 'UUcxP3vMEVVFafLBasCHcjCg',
        sourceUrl: 'https://www.youtube.com/playlist?list=UUcxP3vMEVVFafLBasCHcjCg',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'play_esaral_neet_prep',
        title: 'NEET Preparation Strategy & Talks',
        description: 'Road To Success expert guidance, daily timetables, focus retention strategies, and NCERT indexing.',
        thumbnailUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&auto=format&fit=crop&q=80',
        teacherId: 'akanksha_mam',
        teacherName: 'eSaral NEET experts',
        instituteId: 'esaral',
        instituteName: 'eSaral',
        subject: 'Biology',
        examType: 'NEET',
        lecturesCount: 4,
        youtubePlaylistId: 'PLV1E-ZJbgTPVM2HpJYJ5PZP0NmdXeuOTW',
        sourceUrl: 'https://www.youtube.com/playlist?list=PLV1E-ZJbgTPVM2HpJYJ5PZP0NmdXeuOTW',
        verified: true,
        createdAt: nowISO
      }
    ];

    playlists.forEach(p => {
      batch.set(doc(db, 'playlists', p.id), p);
    });

    // 5. Standalone Lectures / One-Shots (Section 3 of the PDF)
    const lectures: Lecture[] = [
      {
        id: 'lec_math_cuet_pg',
        title: 'Statistics Marathon Series for competitive levels',
        description: 'Full statistics course, including mean, variance, covariance, and probability distributions.',
        videoUrl: 'https://www.youtube.com/embed/z86-ja0PSn0',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'mohit_tyagi',
        teacherName: 'MathonGo',
        instituteId: 'mathongo',
        instituteName: 'MathonGo',
        duration: '3h 15m',
        viewsCount: 145000,
        likesCount: 12900,
        youtubeVideoId: 'z86-ja0PSn0',
        chapter: 'Statistics',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=z86-ja0PSn0',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_allen_jaipur_analysis',
        title: 'JEE Main Paper Analysis and Detailed Solutions',
        description: 'Exact review of the paper difficulty level, cut-off estimations, and correct step-by-step solutions.',
        videoUrl: 'https://www.youtube.com/embed/Ltbn_ZF-pDs',
        thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'JEE',
        contentType: 'lecture',
        teacherId: 'mohit_tyagi',
        teacherName: 'ALLEN Jaipur',
        instituteId: 'allen_career',
        instituteName: 'ALLEN Career Institute',
        duration: '1h 45m',
        viewsCount: 89000,
        likesCount: 6100,
        youtubeVideoId: 'Ltbn_ZF-pDs',
        chapter: 'Exam Analysis',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=Ltbn_ZF-pDs',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_mathongo_trig_tricks',
        title: 'Trigonometry Formulas Shortcuts & Calculations Tricks',
        description: 'Boost score speeds with smart coordinate tricks and elimination parameters for complex trigonometric ratios.',
        videoUrl: 'https://www.youtube.com/embed/Djq88Ndp2A0',
        thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'mohit_tyagi',
        teacherName: 'MathonGo',
        instituteId: 'mathongo',
        instituteName: 'MathonGo',
        duration: '1h 10m',
        viewsCount: 220000,
        likesCount: 21000,
        youtubeVideoId: 'Djq88Ndp2A0',
        chapter: 'Trigonometry',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=Djq88Ndp2A0',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_zen_goc',
        title: 'General Organic Chemistry (GOC Class 11)',
        description: 'Absolute core mechanisms, carbocations stability, resonance effects, and IUPAC guidelines revisions.',
        videoUrl: 'https://www.youtube.com/embed/0_d_D91cDwU',
        thumbnailUrl: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=400&auto=format&fit=crop&q=80',
        subject: 'Chemistry',
        examType: 'Both',
        contentType: 'oneshot',
        teacherId: 'skm_sir',
        teacherName: 'Zenith Guru',
        duration: '2h 30m',
        viewsCount: 165000,
        likesCount: 14200,
        youtubeVideoId: '0_d_D91cDwU',
        chapter: 'Organic Chemistry',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=0_d_D91cDwU',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_zen_genetics',
        title: 'Principles of Inheritance & Genetics (Class 12)',
        description: 'Mendelian inheritance, chromosome anomalies, pedigree analysis, and gene linkages simplified.',
        videoUrl: 'https://www.youtube.com/embed/VEYABSpg7GM',
        thumbnailUrl: 'https://images.unsplash.com/photo-1579124476582-fc18276f16ab?w=400&auto=format&fit=crop&q=80',
        subject: 'Biology',
        examType: 'NEET',
        contentType: 'oneshot',
        teacherId: 'hc_verma',
        teacherName: 'Zenith Guru',
        duration: '1h 55m',
        viewsCount: 120000,
        likesCount: 9800,
        youtubeVideoId: 'VEYABSpg7GM',
        chapter: 'Genetics',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=VEYABSpg7GM',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_doub_derivatives',
        title: 'Limits & Derivatives Delta Method (Class 11)',
        description: 'First principle derivative limits and slope calculations with board and entry tier samples.',
        videoUrl: 'https://www.youtube.com/embed/oA-MnuolI90',
        thumbnailUrl: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'Both',
        contentType: 'lecture',
        teacherId: 'mohit_tyagi',
        teacherName: 'Doubtnut',
        instituteId: 'doubtnut',
        instituteName: 'Doubtnut',
        duration: '58m',
        viewsCount: 75000,
        likesCount: 4200,
        youtubeVideoId: 'oA-MnuolI90',
        chapter: 'Limits & Derivatives',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=oA-MnuolI90',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_doub_formulas',
        title: 'Empirical and Molecular Formulas Revisions',
        description: 'Learn percent composition, stoichiometric ratios, and finding chemical compound empirical equations.',
        videoUrl: 'https://www.youtube.com/embed/UnZyvtwz5DA',
        thumbnailUrl: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5c?w=400&auto=format&fit=crop&q=80',
        subject: 'Chemistry',
        examType: 'Both',
        contentType: 'lecture',
        teacherId: 'skm_sir',
        teacherName: 'Doubtnut',
        instituteId: 'doubtnut',
        instituteName: 'Doubtnut',
        duration: '48m',
        viewsCount: 64000,
        likesCount: 3900,
        youtubeVideoId: 'UnZyvtwz5DA',
        chapter: 'Some Basic Concepts of Chemistry',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=UnZyvtwz5DA',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_jw_relations',
        title: 'Relations and Functions - Complete Class 12 One-Shot',
        description: 'Detailed theoretical explanations, equivalence relations, surjective injective mapping with multiple JEE samples.',
        videoUrl: 'https://www.youtube.com/embed/Qs0wRt70mC4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'mohit_tyagi',
        teacherName: 'JEE Wallah (PW)',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        duration: '4h 10m',
        viewsCount: 510000,
        likesCount: 48000,
        youtubeVideoId: 'Qs0wRt70mC4',
        chapter: 'Relations and Functions',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=Qs0wRt70mC4',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_jw_periodic',
        title: 'Periodic Table and Chemistry Periodicity One-Shot',
        description: 'Comprehensive block elements categorization, ionization energies, electron gain enthalpies, and periodic trends.',
        videoUrl: 'https://www.youtube.com/embed/nLE7_YBFQNQ',
        thumbnailUrl: 'https://images.unsplash.com/photo-1532187643603-ba119ca4109e?w=400&auto=format&fit=crop&q=80',
        subject: 'Chemistry',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'skm_sir',
        teacherName: 'JEE Wallah (PW)',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        duration: '3h 40m',
        viewsCount: 420000,
        likesCount: 39000,
        youtubeVideoId: 'nLE7_YBFQNQ',
        chapter: 'Classification of Elements',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=nLE7_YBFQNQ',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_jw_modern',
        title: 'Modern Physics Class 12 One-Shot Booster',
        description: 'Master dual nature of matter, photoelectric effects, Bohr\'s atomic structure, and nuclear reactions for JEE/NEET.',
        videoUrl: 'https://www.youtube.com/embed/V76QPpoWVwA',
        thumbnailUrl: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=400&auto=format&fit=crop&q=80',
        subject: 'Physics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'alakh_pandey',
        teacherName: 'JEE Wallah (PW)',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        duration: '5h 15m',
        viewsCount: 650000,
        likesCount: 54000,
        youtubeVideoId: 'V76QPpoWVwA',
        chapter: 'Modern Physics',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=V76QPpoWVwA',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_ved_made_ejee_phys',
        title: 'Complete Physics Final High-Yield Revision',
        description: 'Fast-paced revision, formulas summaries, boundary conditions derivation for boards and entrance mocks.',
        videoUrl: 'https://www.youtube.com/embed/bs9GchrXEew',
        thumbnailUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&auto=format&fit=crop&q=80',
        subject: 'Physics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'nv_sir',
        teacherName: 'Vedantu JEE Made Ejee',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        duration: '2h 15m',
        viewsCount: 198000,
        likesCount: 15600,
        youtubeVideoId: 'bs9GchrXEew',
        chapter: 'Physics Revisions',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=bs9GchrXEew',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_ved_eng_marathon',
        title: 'Complete Physics Marathon in English',
        description: 'Elite level physics chapter concepts structured explicitly to review kinematics, dynamics and thermodynamics.',
        videoUrl: 'https://www.youtube.com/embed/faYrSAS5WD8',
        thumbnailUrl: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?w=400&auto=format&fit=crop&q=80',
        subject: 'Physics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'nv_sir',
        teacherName: 'Vedantu JEE English',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        duration: '6h 30m',
        viewsCount: 310000,
        likesCount: 28000,
        youtubeVideoId: 'faYrSAS5WD8',
        chapter: 'Full Physics',
        language: 'English',
        sourceUrl: 'https://www.youtube.com/watch?v=faYrSAS5WD8',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_ved_vaathi_organic',
        title: 'Organic Chemistry Class 11 Part 2 in English',
        description: 'Comprehensive English lectures exploring functional groups, IUPAC guidelines, aromatic compounds reactions.',
        videoUrl: 'https://www.youtube.com/embed/iNybFscNU7Y',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511225010778-19335a434b81?w=400&auto=format&fit=crop&q=80',
        subject: 'Chemistry',
        examType: 'JEE',
        contentType: 'lecture',
        teacherId: 'skm_sir',
        teacherName: 'Vedantu JEE Vaathi',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        duration: '1h 35m',
        viewsCount: 124000,
        likesCount: 8900,
        youtubeVideoId: 'iNybFscNU7Y',
        chapter: 'Organic Chemistry',
        language: 'English',
        sourceUrl: 'https://www.youtube.com/watch?v=iNybFscNU7Y',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_ved_shm_oneshot',
        title: 'Simple Harmonic Motion (SHM) One-Shot',
        description: ' Kota standard equations derivations, spring-mass systems, pendulums, and damped oscillations parameters.',
        videoUrl: 'https://www.youtube.com/embed/kMPFWpjl1hQ',
        thumbnailUrl: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?w=400&auto=format&fit=crop&q=80',
        subject: 'Physics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'nv_sir',
        teacherName: 'Vedantu JEE',
        instituteId: 'vedantu_jee',
        instituteName: 'Vedantu',
        duration: '2h 10m',
        viewsCount: 154000,
        likesCount: 11200,
        youtubeVideoId: 'kMPFWpjl1hQ',
        chapter: 'Simple Harmonic Motion',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=kMPFWpjl1hQ',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_unac_emi_eng',
        title: 'Electromagnetic Induction RRR - Physics in English',
        description: 'Faraday\'s Laws, Lenz\'s Law, self & mutual induction coefficients explained in clean English by RRR Sir.',
        videoUrl: 'https://www.youtube.com/embed/2AL-5eBi570',
        thumbnailUrl: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400&auto=format&fit=crop&q=80',
        subject: 'Physics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'alakh_pandey',
        teacherName: 'Unacademy JEE English',
        instituteId: 'unacademy_jee',
        instituteName: 'Unacademy',
        duration: '3h 15m',
        viewsCount: 185000,
        likesCount: 14750,
        youtubeVideoId: '2AL-5eBi570',
        chapter: 'Electromagnetic Induction',
        language: 'English',
        sourceUrl: 'https://www.youtube.com/watch?v=2AL-5eBi570',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_unac_straight_lines',
        title: 'Straight Lines Class 11 (Sameer Sir)',
        description: 'Slope of lines, angle between straight lines, intercept shapes, distance formulas, and analytical coordinate geometries.',
        videoUrl: 'https://www.youtube.com/embed/vclnl1rSCmM',
        thumbnailUrl: 'https://images.unsplash.com/photo-1509228626622-a61247a3b42a?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'JEE',
        contentType: 'lecture',
        teacherId: 'mohit_tyagi',
        teacherName: 'Sameer Sir',
        instituteId: 'unacademy_jee',
        instituteName: 'Unacademy',
        duration: '1h 50m',
        viewsCount: 224000,
        likesCount: 19500,
        youtubeVideoId: 'vclnl1rSCmM',
        chapter: 'Straight Lines',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=vclnl1rSCmM',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_atoms_relations',
        title: 'Relations and Functions - BounceBack series',
        description: 'Unacademy Atoms specialized high speed revision course covering direct composite mappings and function domain ranges.',
        videoUrl: 'https://www.youtube.com/embed/__XBcqZl5oQ',
        thumbnailUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
        subject: 'Mathematics',
        examType: 'JEE',
        contentType: 'oneshot',
        teacherId: 'mohit_tyagi',
        teacherName: 'Unacademy Atoms',
        instituteId: 'unacademy',
        instituteName: 'Unacademy',
        duration: '3h 45m',
        viewsCount: 412000,
        likesCount: 38400,
        youtubeVideoId: '__XBcqZl5oQ',
        chapter: 'Relations & Functions',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=__XBcqZl5oQ',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_unac_magnetic',
        title: 'Magnetic Fields & Electromagnetism (Jayant Sir)',
        description: 'Biot-Savart Law, Ampere\'s circuital logs, magnetic forces on particles in uniform electric fields.',
        videoUrl: 'https://www.youtube.com/embed/WZ-Y2biaY20',
        thumbnailUrl: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=400&auto=format&fit=crop&q=80',
        subject: 'Physics',
        examType: 'JEE',
        contentType: 'lecture',
        teacherId: 'alakh_pandey',
        teacherName: 'Jayant Sir',
        instituteId: 'unacademy_jee',
        instituteName: 'Unacademy',
        duration: '1h 24m',
        viewsCount: 156000,
        likesCount: 11900,
        youtubeVideoId: 'WZ-Y2biaY20',
        chapter: 'Moving Charges & Magnetism',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=WZ-Y2biaY20',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_sour_angiosperm',
        title: 'NEET Biology - Angiosperm Families (Sourav Sir)',
        description: 'Morphology of flowering biological structures, floral formulas, and identification of key angiosperm families.',
        videoUrl: 'https://www.youtube.com/embed/nFvoFmR2Upc',
        thumbnailUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&auto=format&fit=crop&q=80',
        subject: 'Biology',
        examType: 'NEET',
        contentType: 'lecture',
        teacherId: 'hc_verma',
        teacherName: 'Sourav Sir`s Classes',
        duration: '1h 05m',
        viewsCount: 94000,
        likesCount: 5200,
        youtubeVideoId: 'nFvoFmR2Upc',
        chapter: 'Morphology of Flowering Plants',
        language: 'English/Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=nFvoFmR2Upc',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_neetp_human_repr',
        title: 'NCERT Discrepancy: Human Reproduction',
        description: 'Crucial detailed discussion on conflicting facts within newer vs older NCERT printings for medical aspirants.',
        videoUrl: 'https://www.youtube.com/embed/C-_IugUlmwQ',
        thumbnailUrl: 'https://images.unsplash.com/photo-1579124476582-fc18276f16ab?w=400&auto=format&fit=crop&q=80',
        subject: 'Biology',
        examType: 'NEET',
        contentType: 'lecture',
        teacherId: 'hc_verma',
        teacherName: 'NEETprep Course',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        duration: '1h 12m',
        viewsCount: 182000,
        likesCount: 15400,
        youtubeVideoId: 'C-_IugUlmwQ',
        chapter: 'Human Reproduction',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=C-_IugUlmwQ',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_neetp_mole',
        title: 'Mole Concept - Chemistry NCERT Analysis (Shashi Sir)',
        description: 'Complete calculation methods of molarities, molalities, equivalent weights, and ideal molecular proportions.',
        videoUrl: 'https://www.youtube.com/embed/-E2X9GflrCg',
        thumbnailUrl: 'https://images.unsplash.com/photo-1511225010778-19335a434b81?w=400&auto=format&fit=crop&q=80',
        subject: 'Chemistry',
        examType: 'NEET',
        contentType: 'lecture',
        teacherId: 'skm_sir',
        teacherName: 'Shashi Sir',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        duration: '1h 25m',
        viewsCount: 142000,
        likesCount: 12900,
        youtubeVideoId: '-E2X9GflrCg',
        chapter: 'Some Basic Concepts of Chemistry',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=-E2X9GflrCg',
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'lec_neetp_respiration',
        title: 'Respiration in Plants MCQ Practice Course',
        description: 'Dr. NK Sharma reviews high-frequency questions of plant glycolysis, Krebs Cycle and electron transport chains.',
        videoUrl: 'https://www.youtube.com/embed/Wb4qjtCHCE4',
        thumbnailUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=400&auto=format&fit=crop&q=80',
        subject: 'Biology',
        examType: 'NEET',
        contentType: 'lecture',
        teacherId: 'hc_verma',
        teacherName: 'Dr. NK Sharma',
        instituteId: 'neetprep',
        instituteName: 'NEETprep',
        duration: '1h 05m',
        viewsCount: 110000,
        likesCount: 8900,
        youtubeVideoId: 'Wb4qjtCHCE4',
        chapter: 'Respiration in Plants',
        language: 'Hinglish',
        sourceUrl: 'https://www.youtube.com/watch?v=Wb4qjtCHCE4',
        verified: true,
        createdAt: nowISO
      }
    ];

    lectures.forEach(lec => {
      batch.set(doc(db, 'lectures', lec.id), lec);
    });

    // 6. Batches Seeding (Section 4 of the PDF)
    const batches: Batch[] = [
      {
        id: 'batch_arjuna_neet_2027_pw',
        name: 'Arjuna NEET 2027 Complete Course',
        description: 'Interactive cohort design strictly centered on medical entrance prep. Includes daily assignments, live lectures & doubt engines.',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        teachers: ['Alakh Pandey'],
        subject: 'Full Course',
        examType: 'NEET',
        startDate: '2026-04-13',
        endDate: '2027-01-31',
        link: 'https://www.pw.live/neet/exams/pw-arjuna-neet-2027-batch',
        price: 3900,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_lakshya_neet_2027_pw',
        name: 'Lakshya NEET 2027 Class 12 Batch',
        description: 'Complete structured roadmap covering Grade 12 Biology, Organic chemistry and electrical Physics.',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        teachers: ['Alakh Pandey'],
        subject: 'Full Course',
        examType: 'NEET',
        startDate: '2026-03-25',
        endDate: '2027-06-30',
        link: 'https://www.pw.live/neet/class-12/batches/lakshya-neet-2027-018988',
        price: 4200,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_arjuna_lakshya_jee_pw',
        name: 'Arjuna JEE 2026 + Lakshya JEE 2027',
        description: 'Specialized 2-year integrated course offering robust foundation and rank Booster revisions. Weekly CBT simulations included.',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        teachers: ['Alakh Pandey'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2025-04-14',
        endDate: '2026-12-31',
        link: 'https://www.pw.live/iit-jee/class-11/batches/arjuna-jee-2026--lakshya-jee-2027-014953',
        price: 7500,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_arjuna_lakshya_neet_pw',
        name: 'Arjuna NEET 2026 + Lakshya NEET 2027',
        description: 'Comprehensive 2-year integrated clinical stream batch, featuring daily tests and round-the-clock student doubt assistance platforms.',
        instituteId: 'pw',
        instituteName: 'Physics Wallah',
        teachers: ['Alakh Pandey'],
        subject: 'Full Course',
        examType: 'NEET',
        startDate: '2025-04-14',
        endDate: '2026-12-31',
        link: 'https://www.pw.live/neet/class-12/batches/arjuna-neet-2026--lakshya-neet-2027-922371',
        price: 7200,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_praveen_jee_comp',
        name: 'Praveen JEE 2027 Dropper Batch',
        description: 'Fast track comprehensive curriculum designed for complete PCM syllabus revisions in a strict 617 session timeline.',
        instituteId: 'competishun',
        instituteName: 'Competishun',
        teachers: ['Mohit Tyagi', 'SKM Sir'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2026-06-15',
        endDate: '2026-12-20',
        link: 'https://competishun.com/praveen/',
        price: 18500,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_pratham_jee2028_comp',
        name: 'Pratham JEE 2028 Foundation',
        description: 'High-concept coordinate systems, logarithms and kinematics basics structural batch, ideal for Class 11 starting pupils.',
        instituteId: 'competishun',
        instituteName: 'Competishun',
        teachers: ['Mohit Tyagi'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2026-06-15',
        endDate: '2027-02-28',
        link: 'https://competishun.com/pratham/',
        price: 15000,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_nimbus_alpha_unac',
        name: 'Nimbus Alpha 2.0 Batch for IIT JEE 2028',
        description: 'Elite level physical center classroom cohort structure streamed live with top educators in the evenings.',
        instituteId: 'unacademy',
        instituteName: 'Unacademy',
        teachers: ['Anupam Gupta'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2026-06-12',
        endDate: '2028-04-15',
        link: 'https://unacademy.com/goal/jee-main-and-advanced-preparation/TMUVD',
        price: 34999,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_nimbus_legends_unac',
        name: 'Nimbus Legends 2.0 Batch for IIT JEE 2028',
        description: 'Advanced mathematics and mechanics booster system covering top ranks questions and past paper analysis.',
        instituteId: 'unacademy',
        instituteName: 'Unacademy',
        teachers: ['Anupam Gupta'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2026-06-14',
        endDate: '2028-04-15',
        link: 'https://unacademy.com/goal/jee-main-and-advanced-preparation/TMUVD',
        price: 38999,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_bounce_back_unac',
        name: 'Bounce Back – JEE Preparation for Class 12',
        description: 'Morning and evening sessions covering standard Class 12 PCM topics, physics derivations and analytical formulas.',
        instituteId: 'unacademy',
        instituteName: 'Unacademy',
        teachers: ['Anupam Gupta'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2026-06-14',
        endDate: '2027-05-02',
        link: 'https://unacademy.com/goal/jee-main-and-advanced-preparation/TMUVD/browse',
        price: 19999,
        verified: true,
        createdAt: nowISO
      },
      {
        id: 'batch_level_up_unac',
        name: 'Level Up – JEE Preparation for Class 11',
        description: 'Foundational trigonometry, structural vector dynamics and organic carbon definitions, engineered to build confidence.',
        instituteId: 'unacademy',
        instituteName: 'Unacademy',
        teachers: ['Anupam Gupta'],
        subject: 'Full Course',
        examType: 'JEE',
        startDate: '2026-06-15',
        endDate: '2027-05-15',
        link: 'https://unacademy.com/goal/jee-main-and-advanced-preparation/TMUVD',
        price: 18499,
        verified: true,
        createdAt: nowISO
      }
    ];

    batches.forEach(b => {
      batch.set(doc(db, 'batches', b.id), b);
    });

    await batch.commit();
    console.log('Successfully completed seeding official high-fidelity JEE/NEET content database! Total playists seeded:', playlists.length);
  } catch (error) {
    console.error('Seeding failed or aborted with exception:', error);
  }
}
